/*
 *
 * FoundPage constants
 *
 */

export const DEFAULT_ACTION = 'app/FoundPage/DEFAULT_ACTION';

export const CHANGE_TAB = 'app/FoundPage/CHANGE_TAB';

export const LOAD_DISCOVERIES_DATA = 'app/FoundPage/LOAD_DISCOVERIES_DATA';
export const LOAD_DISCOVERIES_DATA_SUCCESS = 'app/FoundPage/LOAD_DISCOVERIES_DATA_SUCCESS';
export const LOAD_DISCOVERIES_DATA_ERROR = 'app/FoundPage/LOAD_DISCOVERIES_DATA_ERROR';

export const LOAD_RECOMMENDATION_DATA = 'app/FoundPage/LOAD_RECOMMENDATION_DATA';
export const LOAD_RECOMMENDATION_DATA_SUCCESS = 'app/FoundPage/LOAD_RECOMMENDATION_DATA_SUCCESS';
export const LOAD_RECOMMENDATION_DATA_ERROR = 'app/FoundPage/LOAD_RECOMMENDATION_DATA_ERROR';


