export const DEFAULT_ACTION = 'app/AuthorAttestPage/DEFAULT_ACTION';

export const LOAD_AUTHORATTEST_DATA = 'app/AuthorAttestPage/LOAD_AUTHORATTEST_DATA';
export const LOAD_AUTHORATTEST_DATA_SUCCESS = 'app/AuthorAttestPage/LOAD_AUTHORATTEST_DATA_SUCCESS';
export const LOAD_AUTHORATTEST_DATA_ERROR = 'app/AuthorAttestPage/LOAD_AUTHORATTEST_DATA_ERROR';

export const SET_AUTHORATTEST_DATA = 'app/AuthorAttestPage/SET_AUTHORATTEST_DATA';

export const UPDATE_AUTHORATTEST_DATA = 'app/AuthorAttestPage/UPDATE_AUTHORATTEST_DATA';
export const UPDATE_AUTHORATTEST_DATA_SUCCESS = 'app/AuthorAttestPage/UPDATE_AUTHORATTEST_DATA_SUCCESS';
export const UPDATE_AUTHORATTEST_DATA_ERROR = 'app/AuthorAttestPage/UPDATE_AUTHORATTEST_DATA_ERROR';
