export const DEFAULT_ACTION = 'app/ServicePersonalPage/DEFAULT_ACTION';

export const LOAD_SERVICEPERSONAL_DATA = 'app/ServicePersonalPage/LOAD_SERVICEPERSONAL_DATA';
export const LOAD_SERVICEPERSONAL_DATA_SUCCESS = 'app/ServicePersonalPage/LOAD_SERVICEPERSONAL_DATA_SUCCESS';
export const LOAD_SERVICEPERSONAL_DATA_ERROR = 'app/ServicePersonalPage/LOAD_SERVICEPERSONAL_DATA_ERROR';

export const SET_SERVICEPERSONAL_DATA = 'app/ServicePersonalPage/SET_SERVICEPERSONAL_DATA';

export const UPDATE_SERVICEPERSONAL_DATA = 'app/ServicePersonalPage/UPDATE_SERVICEPERSONAL_DATA';
export const UPDATE_SERVICEPERSONAL_DATA_SUCCESS = 'app/ServicePersonalPage/UPDATE_SERVICEPERSONAL_DATA_SUCCESS';
export const UPDATE_SERVICEPERSONAL_DATA_ERROR = 'app/ServicePersonalPage/UPDATE_SERVICEPERSONAL_DATA_ERROR';