export const DEFAULT_ACTION = 'app/ServiceAgencyPage/DEFAULT_ACTION';

export const LOAD_SERVICEAGENCY_DATA = 'app/ServiceAgencyPage/LOAD_SERVICEAGENCY_DATA';
export const LOAD_SERVICEAGENCY_DATA_SUCCESS = 'app/ServiceAgencyPage/LOAD_SERVICEAGENCY_DATA_SUCCESS';
export const LOAD_SERVICEAGENCY_DATA_ERROR = 'app/ServiceAgencyPage/LOAD_SERVICEAGENCY_DATA_ERROR';

export const SET_SERVICEAGENCY_DATA = 'app/ServiceAgencyPage/SET_SERVICEAGENCY_DATA';

export const UPDATE_SERVICEAGENCY_DATA = 'app/ServiceAgencyPage/UPDATE_SERVICEAGENCY_DATA';
export const UPDATE_SERVICEAGENCY_DATA_SUCCESS = 'app/ServiceAgencyPage/UPDATE_SERVICEAGENCY_DATA_SUCCESS';
export const UPDATE_SERVICEAGENCY_DATA_ERROR = 'app/ServiceAgencyPage/UPDATE_SERVICEAGENCY_DATA_ERROR';