export const DEFAULT_ACTION = 'app/AttestStatePage/DEFAULT_ACTION';

export const LOAD_ATTESTSTATE_DATA = 'app/AttestStatePage/LOAD_ATTESTSTATE_DATA';
export const LOAD_ATTESTSTATE_DATA_SUCCESS = 'app/AttestStatePage/LOAD_ATTESTSTATE_DATA_SUCCESS';
export const LOAD_ATTESTSTATE_DATA_ERROR = 'app/AttestStatePage/LOAD_ATTESTSTATE_DATA_ERROR';
